### ISSUE TITLE
unknown ssh-add option

### ISSUE THREAD

**Issue by ThomasWaldmann** [carmstrong/multinode-ceph-vagrant#10]
From the readme:
```
$ ssh-add -K ~/.vagrant.d/insecure_private_key
```

My ssh-add does not know `-K` - should that be `-k`?

**Comment by carmstrong** [comment]
> My ssh-add does not know -K - should that be -k?

I think it depends on the client - the flags differ. On my Mac it's `-K`, but on some Linux distros, I think it's `-k`. Maybe a note would suffice with both examples?

**Comment by ThomasWaldmann** [comment]
thanks!
