### ISSUE TITLE
clock skew issues

### ISSUE THREAD

**Issue by ThomasWaldmann** [carmstrong/multinode-ceph-vagrant#13]
After bringing up the vagrant machines and fixing some other problems, I always had the health check fail due to clock skew (about 1s difference).

First tried to install and use ntp(d), but that somehow did not work ok. Then I remembered reading that running ntp is not advised for VMs.

Then found that the clock sync provided by virtualbox guest tools works rather slowly by trying to smoothly adjust the clock and has a high threshold (20mins clock difference) for immediate adjustment.

As ceph requires less than 50ms clock skew, I added this to the Vagrantfile:
```
  config.vm.provider 'virtualbox' do |vb|
    vb.customize [ "guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 50 ]
    vb.customize [ "guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-start", 1 ]
    vb.customize [ "guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-interval", 1000 ]
  end
```

So, if the clock is off by >= 50ms, it will get adjusted immediately.

**Comment by ThomasWaldmann** [comment]
Hmm, that somehow improved the situation, but does not seem to reliably and permanently fix the issue.

Better ideas?

**Comment by ta1hia** [comment]
Any updates on this issue? From [this wiki](https://wiki.deimos.fr/Ceph_:_performance,_reliability_and_scalability_storage_solution#health_HEALTH_WARN_clock_skew_detected), I added the following to ceph.conf:

```
[global]
    mon_clock_drift_allowed = 1
```

The default allowed clock drift is half a millisecond so this increases the value to help suppress the warning. Not a fix but was enough to get the example running.

**Comment by carmstrong** [comment]
I think `mon_clock_drift_allowed` makes sense. I would have to use this on my machine if it resumed from sleep - the clocks would be a bit skewed. Does someone have time to PR this change after confirming?
