### ISSUE TITLE
show --release option in the readme

### ISSUE THREAD

**Issue by ThomasWaldmann** [carmstrong/multinode-ceph-vagrant#14]
`ceph-deploy install` currently still uses 10.2.5 (not 11, although it is released).

guess a lot of people would like to play with bluestore, so adding the --release option might be nice:

```
-ceph-deploy install ceph-admin ceph-server-1 ceph-server-2 ceph-server-3 ceph-client
+ceph-deploy install --release=luminous ceph-admin ceph-server-1 ceph-server-2 ceph-server-3 ceph-client
```

Depending on what you target, maybe don't add luminous, but show the option, so it is obvious where to give that. (just using a different debian-xxxxx repo is not enough)

**Comment by carmstrong** [comment]
Sounds like a good change! Care to PR it?

**Comment by ThomasWaldmann** [comment]
thanks!
