### ISSUE TITLE
RBD image feature set mismatch

### ISSUE THREAD

**Issue by gator1** [carmstrong/multinode-ceph-vagrant#17]
Hi,
Great work. 

I followed your instructions (only to change names of the servers to mon-1--3 and osd-1--3). 
I got the status as HEALTH_OK with three osd in and up. 

When I tried to map a rbd I got this. 

Do you have the same issue? Do you know how to fix it?

In the general term, how do you manage virtualbox ubuntu VM to manage drives? 

vagrant@ceph-client:~$ sudo rbd create foo --size 4096 -m mon-1
vagrant@ceph-client:~$ sudo rbd map foo --pool rbd --name client.admin -m mon-1
rbd: sysfs write failed
RBD image feature set mismatch. You can disable features unsupported by the kernel with "rbd feature disable".
In some cases useful info is found in syslog - try "dmesg | tail" or so.
rbd: map failed: (6) No such device or address

**Comment by gator1** [comment]
need to do this 
rbd create --size 4096 docker_test --image-feature layering

**Comment by moiseevigor** [comment]
@gator1 thanks, it took a while to find this issue
