### ISSUE TITLE
rbd: error opening default pool 'rbd'

### ISSUE THREAD

**Issue by verbunk** [carmstrong/multinode-ceph-vagrant#23]
Following the README there are a couple of additions I needed, 

Following, 
vagrant@ceph-admin:~/test-cluster$ ssh ceph-server-3 sudo chmod +r /etc/ceph/ceph.client.admin.keyring

Do, 

## Create Manager
vagrant@ceph-admin:~/test-cluster$ ceph-deploy mgr create ceph-admin:mon_mgr

####
Following, 
vagrant@ceph-admin:~/test-cluster$ ceph quorum_status --format json-pretty

Do, 
## Create a default rbd pool
vagrant@ceph-admin:~/test-cluster$ ceph osd pool create rbd 150 150

In case this helps someone else.

**Comment by sysarcher** [comment]
haah... I was here to create this issue and propose this solution :+1:

**Comment by carmstrong** [comment]
Thanks for the report. I haven't had time to visit this repo in a long time, but I've been meaning to make it more up-to-date. If you'd be willing to open a PR, I'd be happy to review.

**Comment by sysarcher** [comment]
@carmstrong I submitted PR #24 that should close this issue
