### ISSUE TITLE
Permission Issue on osd activate command

### ISSUE THREAD

**Issue by brownie1** [carmstrong/multinode-ceph-vagrant#5]
There is a permission denied issue when running the activate command. The issue is that when the /var/local/osd0 and osd1 directories are created the permissions are for root:staff. Changing the line to ssh ceph-server-2 "sudo mkdir /var/local/osd0 && sudo chown ceph:ceph /var/local/osd0" will fix the issue.

**Comment by carmstrong** [comment]
Thanks for the fix. Wold you mind PRing a fix?

**Comment by carmstrong** [comment]
I think this was resolved in #7.
